GOOGLE_API_KEY = "AIzaSyDsxYEZY7TQf3okVlQxPIEDJ7e0EOKAckw"

MONGO_CONNECTION_STRING = "mongodb+srv://arslab:71QFq59ptwaIXpuh@msdschatbot.gbvbi.mongodb.net/?retryWrites=true&w=majority&appName=MSDSchatbot"